version: '2.2'
services:
  relay:
    image: svforte/anon:db842126d232bebd7a41fa759016bf9ea2ed4b59
    container_name: anon-relay
    init: true
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /data/anon/var/lib/anon/:/var/lib/anon/
      - /data/anon/etc/anon/:/etc/anon/
      - /data/anon/run/anon/:/run/anon/ #Optional dir for NYX
