version: '2.2'
services:
  relay:
    image: svforte/anon:a76c258d6a9ebe83c888fc50d64efc0bd3a980f3
    container_name: anon-relay
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /data/anon/var/lib/anon/:/var/lib/anon/
      - /data/anon/etc/anon/:/etc/anon/
      - /data/anon/run/anon/:/run/anon/ #Optional dir for NYX
